- job:
    name: "cleanup-tf-dev-sandbox"
    description: "Manually triggered job to remove tf-dev-sandbox image from nexus registries"
    defaults: global
    concurrent: false
    properties:
      - build-discarder:
          num-to-keep: 30
    node: openstack
    scm:
      - tf-jenkins
    wrappers:
      - workspace-cleanup:
          disable-deferred-wipeout: true
      - timestamps
      - credentials-binding:
          - ssh-user-private-key:
              credential-id: logs_host
              key-file-variable: LOGS_HOST_SSH_KEY
              username-variable: LOGS_HOST_USERNAME
    builders:
      - shell: |
          ./src/opensdn-io/tf-jenkins/infra/cleanup-tf-dev-sandbox.sh
          SSH_OPTIONS="-T -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no"
          LOGS_HOST="nexus.$SLAVE_REGION.$CI_DOMAIN"
          ssh -i $LOGS_HOST_SSH_KEY $SSH_OPTIONS $LOGS_HOST_USERNAME@$LOGS_HOST "rm -f /var/www/logs/frozen/tag"
