---

- job:
    name: "update-tpc-source-repository"
    description: "Update tpc-source repository from tf-third-party-packages"
    defaults: global
    properties:
      - build-discarder:
          num-to-keep: 30
    node: openstack
    concurrent: false
    scm:
      - tf-jenkins
      - tf-dev-env
    parameters:
      - choice:
          description: "TPC version to update"
          name: TPC_VERSION
          choices:
            - el7
            - el8
    wrappers:
      - workspace-cleanup:
          disable-deferred-wipeout: true
      - timestamps
      - credentials-binding:
          - ssh-user-private-key:
              credential-id: worker
              key-file-variable: WORKER_SSH_KEY
              username-variable: WORKER_USER_NAME
              passphrase-variable: WORKER_PASSPHRASE
      # - credentials-binding:
      #     - amazon-web-services:
      #         credential-id: aws-creds
      #         access-key: AWS_ACCESS_KEY_ID
      #         secret-key: AWS_SECRET_ACCESS_KEY
      - credentials-binding:
          - text:
              credential-id: OS_USERNAME
              variable: OS_USERNAME
          - text:
              credential-id: OS_PROJECT_ID
              variable: OS_PROJECT_ID
          - text:
              credential-id: OS_PASSWORD
              variable: OS_PASSWORD
          - text:
              credential-id: OS_DOMAIN_NAME
              variable: OS_USER_DOMAIN_NAME
          - text:
              credential-id: OS_DOMAIN_NAME
              variable: OS_PROJECT_DOMAIN_NAME
          - text:
              credential-id: OS_AUTH_URL
              variable: OS_AUTH_URL
          - username-password-separated:
              credential-id: tpc-repo
              username: TPC_REPO_USER
              password: TPC_REPO_PASS
    builders:
      - shell: |
          # individual job - create global.env
          echo "export SLAVE=openstack" > $WORKSPACE/global.env
          echo "export REPOS_CHANNEL=latest" >> $WORKSPACE/global.env
          echo "export TPC_VERSION=$TPC_VERSION" >> $WORKSPACE/global.env
          if [[ $TPC_VERSION == 'el7' ]]; then
            echo "export ENVIRONMENT_OS=centos7" >> $WORKSPACE/global.env
          else
            # el8 case
            #echo "export ENVIRONMENT_OS=centos8" >> $WORKSPACE/global.env
            echo "export LINUX_DISTR_VER=8" >> $WORKSPACE/global.env
          fi
      - shell: |
          set -eo pipefail
          source "$WORKSPACE/global.env"

          ./src/opensdn-io/tf-jenkins/jobs/update-tpc/create_workers.sh
          source "$WORKSPACE/stackrc.$JOB_NAME.env"
          # main run
          ./src/opensdn-io/tf-jenkins/jobs/update-tpc/run.sh || res=1
          # collect logs
          ./src/opensdn-io/tf-jenkins/jobs/update-tpc/collect_logs.sh
          exit $res
    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                - SUCCESS
                - FAILURE
                - ABORTED
                - NOT_BUILT
                - UNSTABLE
              build-steps:
                - shell: |
                    source "$WORKSPACE/global.env"
                    if [ -e "$WORKSPACE/stackrc.$JOB_NAME.env" ]; then
                      echo "INFO: stackrc file found. remove workers."
                      source "$WORKSPACE/stackrc.$JOB_NAME.env"
                      ./src/opensdn-io/tf-jenkins/infra/$SLAVE/remove_workers.sh
                    else
                      echo "INFO: stackrc file could not be found."
                    fi
                    rm -f "$WORKSPACE/stackrc.$JOB_NAME.env"
      - archive:
          artifacts: '*.env'
