---

- job:
    name: "update-tpc-source-repository"
    description: "Update tpc-source repository from tf-third-party-packages"
    defaults: global
    node: vexxhost
    concurrent: false
    scm:
      - tf-jenkins
      - tf-dev-env
    wrappers:
      - workspace-cleanup:
          disable-deferred-wipeout: true
      - timestamps
      - credentials-binding:
          - ssh-user-private-key:
              credential-id: worker
              key-file-variable: WORKER_SSH_KEY
              username-variable: WORKER_USER_NAME
              passphrase-variable: WORKER_PASSPHRASE
      - credentials-binding:
          - amazon-web-services:
              credential-id: aws-creds
              access-key: AWS_ACCESS_KEY_ID
              secret-key: AWS_SECRET_ACCESS_KEY
      - credentials-binding:
          - text:
              credential-id: VEXX_OS_USERNAME
              variable: OS_USERNAME
          - text:
              credential-id: VEXX_OS_PROJECT_NAME
              variable: OS_PROJECT_NAME
          - text:
              credential-id: VEXX_OS_PASSWORD
              variable: OS_PASSWORD
          - text:
              credential-id: VEXX_OS_DOMAIN_NAME
              variable: OS_USER_DOMAIN_NAME
          - text:
              credential-id: VEXX_OS_DOMAIN_NAME
              variable: OS_PROJECT_DOMAIN_NAME
          - text:
              credential-id: VEXX_OS_AUTH_URL
              variable: OS_AUTH_URL
          - text:
              credential-id: TPC_REPO_USER
              variable: TPC_REPO_USER
          - text:
              credential-id: TPC_REPO_PASS
              variable: TPC_REPO_PASS
    builders:
      - shell: |
          # individual job - create global.env
          echo "export SLAVE=vexxhost" > $WORKSPACE/global.env
          echo "export ENVIRONMENT_OS=centos7" >> $WORKSPACE/global.env
      - shell: |
          set -eo pipefail
          source "$WORKSPACE/global.env"

          ./src/tungstenfabric/tf-jenkins/jobs/update-tpc/create_workers.sh
          source "$WORKSPACE/stackrc.$JOB_NAME.env"
          # main run
          ./src/tungstenfabric/tf-jenkins/jobs/update-tpc/run.sh || res=1
          # collect logs
          ./src/tungstenfabric/tf-jenkins/jobs/update-tpc/collect_logs.sh
          exit $res
    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                - SUCCESS
                - FAILURE
                - ABORTED
                - NOT_BUILT
                - UNSTABLE
              build-steps:
                - shell: |
                    source "$WORKSPACE/global.env"
                    if [ -e "$WORKSPACE/stackrc.$JOB_NAME.env" ]; then
                      echo "INFO: stackrc file found. remove workers."
                      source "$WORKSPACE/stackrc.$JOB_NAME.env"
                      ./src/tungstenfabric/tf-jenkins/infra/$SLAVE/remove_workers.sh
                    else
                      echo "INFO: stackrc file could not be found."
                    fi
                    rm -f "$WORKSPACE/stackrc.$JOB_NAME.env"
      - archive:
          artifacts: '*.env'
