- job:
    name: "update-prepared-images"
    description: "update-prepared-images"
    defaults: global
    properties:
      - build-discarder:
          num-to-keep: 30
    node: openstack
#    triggers:
#      - timed: 'H H(3-4) * * 1'
    parameters:
      - choice:
          name: IMAGE_TYPE
          choices:
            - ALL
            - CENTOS7
            - CENTOS8
            # - RHEL7
            # - RHEL82
            # - RHEL84
            - UBUNTU18
            - UBUNTU20
            - UBUNTU22
            - RHCOS45
          description: "Image type for update or ALL(default)"
    scm:
      - tf-jenkins
    wrappers:
      - workspace-cleanup:
          disable-deferred-wipeout: true
      - timestamps
      - credentials-binding:
          - text:
              credential-id: OS_USERNAME
              variable: OS_USERNAME
          - text:
              credential-id: OS_PROJECT_ID
              variable: OS_PROJECT_ID
          - text:
              credential-id: OS_PASSWORD
              variable: OS_PASSWORD
          - text:
              credential-id: OS_DOMAIN_NAME
              variable: OS_USER_DOMAIN_NAME
          - text:
              credential-id: OS_DOMAIN_NAME
              variable: OS_PROJECT_DOMAIN_NAME
          - text:
              credential-id: OS_AUTH_URL
              variable: OS_AUTH_URL
        #   - username-password-separated:
        #       credential-id: rhel-creds
        #       username: RHEL_USER
        #       password: RHEL_PASSWORD
    builders:
      - shell: |
          echo "DESCRIPTION Image type=$IMAGE_TYPE"
      - description-setter:
          regexp: "DESCRIPTION (.*)"
      - shell: |
          ./src/tungstenfabric/tf-jenkins/infra/openstack/update_prepared_images.sh
