#!/bin/bash

export VM_BOOT_RETRIES="${VM_BOOT_RETRIES:-120}"
export VM_BOOT_DELAY="${VM_BOOT_DELAY:-60}"

export management_network_name='management'
export provision_network_name='data'

export SSH_OPTIONS="-T -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ServerAliveInterval=60"

function add_deployrc() {
  local file="$1"
  cat "$WORKSPACE/$stackrc_file" >> "$file"
}
export -f add_deployrc
