- job:
    name: "build"
    description: "build"
    defaults: global
    scm:
      - tf-jenkins
      - tf-dev-env
    parameters:
      - label:
          name: SLAVE
      - string:
          name: PIPELINE_BUILD_NUMBER
    wrappers:
      - credentials-binding:
          - ssh-user-private-key:
              credential-id: worker
              key-file-variable: WORKER_SSH_KEY
              username-variable: WORKER_USER_NAME
              passphrase-variable: WORKER_PASSPHRASE
      - credentials-binding:
          - amazon-web-services:
              credential-id: aws-creds
              access-key: AWS_ACCESS_KEY_ID
              secret-key: AWS_SECRET_ACCESS_KEY
    builders:
      - copyartifact:
          project: check-pipeline
          filter: "global.env"
          which-build: specific-build
          build-number: ${PIPELINE_BUILD_NUMBER}
      - shell: |
          # TODO: set OS to rhel for rhel builds
          export ENVIRONMENT_OS=centos7
          source "$WORKSPACE/global.env"
          ./src/progmaticlab/tf-jenkins/jobs/build/create_workers.sh
      - shell: |
          # TODO: pass nexus creds
          export DEBUG=true
          source "$WORKSPACE/global.env"
          env|sort
          ./src/progmaticlab/tf-jenkins/jobs/build/run.sh
      - shell: |
          source "$WORKSPACE/global.env"
          ./src/progmaticlab/tf-jenkins/infra/${SLAVE}/remove_workers.sh
