---

- template:
    name: helm-k8s
    streams:
      helm-k8s:
        vars:
          MONITORING_DEPLOY_TARGET: AIO
          MONITORING_DEPLOYER: helm
          MONITORING_ORCHESTRATOR: k8s
    parents:
      - build-centos
    jobs:
      deploy-platform-helm-k8s:
        stream: helm-k8s
      deploy-tf-helm-k8s:
        stream: helm-k8s
        depends-on:
          - package-centos
          - deploy-platform-helm-k8s
      test-sanity-helm-k8s:
        job-name: test-sanity
        stream: helm-k8s
        depends-on:
          - deploy-tf-helm-k8s
      collect-logs-and-cleanup-helm-k8s:
        job-name: collect-logs-and-cleanup
        stream: helm-k8s
        type: post-hook
        depends-on:
          - deploy-platform-helm-k8s
          - deploy-tf-helm-k8s
          - test-sanity-helm-k8s

- template:
    name: helm-k8s-ha
    streams:
      helm-k8s-ha:
        vars:
          MONITORING_DEPLOY_TARGET: HA
          MONITORING_DEPLOYER: helm
          MONITORING_ORCHESTRATOR: k8s
    parents:
      - build-centos
    jobs:
      deploy-platform-helm-k8s-ha:
        job-name: deploy-platform-helm-k8s
        stream: helm-k8s-ha
        vars:
          NODES: CONTROLLER_NODES:medium:3,AGENT_NODES:small:2
      deploy-tf-helm-k8s-ha:
        job-name: deploy-tf-helm-k8s
        stream: helm-k8s-ha
        depends-on:
          - package-centos
          - deploy-platform-helm-k8s-ha
      test-sanity-helm-k8s-ha:
        job-name: test-sanity
        stream: helm-k8s-ha
        depends-on:
          - deploy-tf-helm-k8s-ha
      collect-logs-and-cleanup-helm-k8s-ha:
        job-name: collect-logs-and-cleanup
        stream: helm-k8s-ha
        type: post-hook
        depends-on:
          - deploy-platform-helm-k8s-ha
          - deploy-tf-helm-k8s-ha
          - test-sanity-helm-k8s-ha

- template:
    name: helm-os
    parents:
      - build-centos
    streams:
      helm-os:
        vars:
          OPENSTACK_VERSION: rocky
          MONITORING_DEPLOY_TARGET: AIO
          MONITORING_DEPLOYER: helm
          MONITORING_ORCHESTRATOR: os
    jobs:
      deploy-platform-helm-os:
        stream: helm-os
      deploy-tf-helm-os:
        stream: helm-os
        depends-on:
          - package-centos
          - deploy-platform-helm-os
      test-sanity-helm-os:
        job-name: test-sanity
        stream: helm-os
        depends-on:
          - deploy-tf-helm-os
      collect-logs-and-cleanup-helm-os:
        job-name: collect-logs-and-cleanup
        stream: helm-os
        type: post-hook
        depends-on:
          - deploy-platform-helm-os
          - deploy-tf-helm-os
          - test-sanity-helm-os

- template:
    name: helm-os-ha
    parents:
      - build-centos
    streams:
      helm-os-ha:
        vars:
          OPENSTACK_VERSION: rocky
          MONITORING_DEPLOY_TARGET: HA
          MONITORING_DEPLOYER: helm
          MONITORING_ORCHESTRATOR: os
    jobs:
      deploy-platform-helm-os-ha:
        job-name: deploy-platform-helm-os
        stream: helm-os-ha
        vars:
          NODES: CONTROLLER_NODES:medium:3,AGENT_NODES:small:2
      deploy-tf-helm-os-ha:
        job-name: deploy-tf-helm-os
        stream: helm-os-ha
        depends-on:
          - package-centos
          - deploy-platform-helm-os-ha
      test-sanity-helm-os-ha:
        job-name: test-sanity
        stream: helm-os-ha
        depends-on:
          - deploy-tf-helm-os-ha
      collect-logs-and-cleanup-helm-os-ha:
        job-name: collect-logs-and-cleanup
        stream: helm-os-ha
        type: post-hook
        depends-on:
          - deploy-platform-helm-os-ha
          - deploy-tf-helm-os-ha
          - test-sanity-helm-os-ha
